name: ecommerce_app
description: A Flutter e-commerce application using Fake Store API

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Network Requests
  http: ^1.2.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Image Caching
  cached_network_image: ^3.3.1
  
  # Form Validation
  form_validator: ^2.1.1
  
  # Logging
  logger: ^2.2.0
  
  # Shared Preferences for local storage
  shared_preferences: ^2.2.2
  
  # Equatable for value equality
  equatable: ^2.0.5
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Static Analysis
  flutter_lints: ^3.0.1
  
  # Mocking for tests
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 